server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

#  cloud:
#    gateway:
#      routes:
#        - id: METRIC-SERVICE
#          uri: lb://METRIC-SERVICE
#          predicates:
#            - Path=/metric/**

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://hostip:8761/eureka
      instance:
        hostname: hostip